name: Adds all issues that don't include the 'project' label to project board and set correct priority

on:
  issues:
    types:
      - opened
      - labeled
      - commented

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: bulatt3/add-to-project-and-label@v0.0.2
        with:
          project-url: https://github.com/orgs/bulatt3/projects/1
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: project
          label-operator: NOT        
          label-map: |
            { "Priority": [ 
              { "label": "\U0001F7E5 priority: critical", "fieldValue": "\U0001F7E5 priority: critical"] },
              { "label": "\U0001F7E7 priority: high", "fieldValue": "\U0001F7E7 priority: high"] },
              { "label": "\U0001F7E8 priority: medium", "fieldValue": "\U0001F7E8 priority: medium"] },
              { "label": "\U0001F7E9 priority: low", "fieldValue": "\U0001F7E9 priority: low"] }
            ]}
