name: Adds all issues that don't include the 'project' label to project board and set correct priority

on:
  issues:
    types:
      - opened
      - labeled
      - commented

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: bulatt3/add-to-project-and-label@v0.0.2
        with:
          project-url: https://github.com/orgs/bulatt3/projects/1
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: project
          label-operator: NOT        
          label-map: |
            { "Priority": [ 
              { "label": "游린 priority: critical", "fieldValue": "游린 priority: critical" },
              { "label": "游릲 priority: high", "fieldValue": "游릲 priority: high" },
              { "label": "游릳 priority: medium", "fieldValue": "游릳 priority: medium" },
              { "label": "游릴 priority: low", "fieldValue": "游릴 priority: low" }
            ]}
